export const peerDependencies: {
    [dependencyName: string]: string
} = {
    '@babel/core': '^7.6.4',
    '@babel/plugin-proposal-class-properties': '^7.5.5',
    '@babel/plugin-proposal-decorators': '^7.6.0',
    '@babel/plugin-proposal-export-default-from': '^7.5.2',
    '@babel/plugin-proposal-object-rest-spread': '^7.6.2',
    '@babel/plugin-transform-runtime': '^7.6.2',
    '@babel/plugin-transform-typescript': '^7.6.3',
    '@babel/preset-env': '^7.6.3',
    '@babel/preset-react': '^7.6.3',
    '@babel/preset-typescript': '^7.6.0',
    '@babel/runtime': '^7.6.3',
    autoprefixer: '^9.7.0',
    'babel-loader': '^8.0.6',
    'babel-plugin-minify-dead-code-elimination': '^0.5.1',
    'css-loader': '^3.2.0',
    "postcss-nested": "^4.1.2",
    'error-overlay-webpack-plugin': '^0.4.1',
    'friendly-errors-webpack-plugin': '^1.7.0',
    'html-webpack-plugin': '^3.2.0',
    lost: '^8.3.1',
    'node-notifier': '^6.0.0',
    'node-sass': '^4.13.0',
    'optimize-css-assets-webpack-plugin': '^5.0.3',
    'postcss-loader': '^3.0.0',
    'postcss-preset-env': '^6.7.0',
    'raw-loader': '^3.1.0',
    'sass-loader': '^8.0.0',
    'style-loader': '^1.0.0',
    'terser-webpack-plugin': '^2.2.1',
    "dts-css-modules-loader": "^1.0.1",
    webpack: '^4.41.2',
    'webpack-bundle-analyzer': '^3.6.0',
    'webpack-dev-server': '^3.9.0',
    'brotli-webpack-plugin': '^1.1.0',
    'compression-webpack-plugin': '^3.0.0',
    'webpack-manifest-plugin': '^2.2.0',
};

export const featureToPeerDependencyMap = {
    base: [
        '@babel/core',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-decorators',
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-transform-runtime',
        '@babel/plugin-transform-typescript',
        '@babel/preset-env',
        '@babel/preset-react',
        '@babel/preset-typescript',
        '@babel/runtime',
        'babel-loader',
        'babel-plugin-minify-dead-code-elimination',
        'css-loader',
        'error-overlay-webpack-plugin',
        'friendly-errors-webpack-plugin',
        'html-webpack-plugin',
        'optimize-css-assets-webpack-plugin',
        'style-loader',
        'terser-webpack-plugin',
        'webpack',
        'webpack-dev-server',
    ],
    sass: ['sass-loader', 'node-sass'],
    postcss: ['postcss-loader', 'postcss-preset-env', 'postcss-nested'],
    autoprefixer: ['autoprefixer'],
    gzipCompression: ['compression-webpack-plugin'],
    brotliCompression: ['brotli-webpack-plugin'],
    manifest: ['webpack-manifest-plugin'],
    dependencyAnalyzer: ['webpack-bundle-analyzer'],
    lostGrid: ['lost'],
    notifications: ['node-notifier'],
    rawLoader: ['raw-loader'],
};
